### ISSUE TITLE
Unable to exit automated testing with pg.db()

### ISSUE THREAD

**Issue by john-** [mojolicious/pg.js#12]
I am pretty confident that the problem I am experiencing is user error or something in my environment.  That said, even high level direction would be appreciated.

My test application builds and runs without any problem that I can see:

https://gitlab.com/john---/test_mojojs

However, with this line the automated testing (done with either `npm build:test` or `npm run build:c8' hangs after all tests are executed:

https://gitlab.com/john---/test_mojojs/-/blob/main/BackEnd/src/models/messages.ts?ref_type=heads#L6

If I comment out that line the test run exists successfully.

If I do an `strace` then I can see it is hanging on this:

```
futex(0x746ff0c, FUTEX_WAIT_PRIVATE, 7, NULL) = 0
futex(0x746ff20, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x746fed0, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 222626
epoll_wait(13, [], 1024, 0)             = 0
epoll_wait(13, 
```
```
% ps ax | grep 222626
 222626 pts/2    Sl+    0:00 npm run build:c8
```
Any ideas as to where I should look?

**Comment by kraih** [comment]
You have to call `db.release()` to make sure the database connection can get closed. This will get nicer once the `using` keyword becomes available in node.js.

**Comment by john-** [comment]
Thanks for the quick response.  That addressed the user error!
